### ISSUE TITLE
Restoring backups

### ISSUE THREAD

**Issue by samillar94** [enricofer/autoSaver#10]
Hi, this looks pretty good.
How do you use the backups? I couldn't see any instructions on restoring - removing the .bak doesn't work.
Many thanks
Sam

**Comment by enricofer** [comment]
You should rename manually the .bak to .qgs 
....But I guess your problem is that the plugin doesn't handle .qgz project files (new compressed project file format, default from QGIS3.2).
I have not had time to adjust the plugin yet so, for now, you should save QGIS in old .qgs format to properly work with the plugin.
